script:
  - make devbuild

matrix:
  include:
  - os: linux
    language: python
    dist: xenial
    sudo: required
    compiler: gcc
    python: 3.7
    before_install:
      - pip install virtualenv
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env: CC=gcc-7
  - os: linux
    language: python
    dist: xenial
    sudo: required
    compiler: gcc
    python: 3.7
    before_install:
      - pip install virtualenv
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
        packages:
          - gcc-8
          - g++-8
    env: CC=gcc-8
  - os: linux
    language: python
    dist: xenial
    sudo: required
    compiler: clang
    python: 3.7
    before_install:
      - pip install virtualenv
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-xenial-6.0
        packages:
          - clang-6.0
          - g++-7
          - gcc-7
    env: CC=clang-6.0
  - os: osx
    osx_image: xcode10.2
    before_install:
      - brew install python
      - brew install pyenv-virtualenv
