language: python

script:
  - pip install virtualenv
  - make devbuild

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    python: 3.7
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env: CC=gcc-7
